print ("Tugas Python")
print ()
nama = input("Masukan Nama Anda :")
pgln = input("Masukan Panggilan :")
nim = input ("Masukan NIM :")
tglhr = input ("Masukan Tanggal Lahir :")
tmlhr = input ("Masukan Tempat Lahir :")
tlpn = input ("Masukan Telepon :")
almt = input ("Masukan Alamat :")
umur = input ("Masukan Umur Anda :")
print ()
print ("Assalamua'laikum")
print ()
print ("Let me introduce my self. my name is",nama,"but you can call me",pgln,
        "My NIM is",nim,"I was born in",tmlhr,"and I am",umur,"years old. I am very gald if you want to invite my house in",almt,
       ". So, don't forget to call me before with the number",tlpn,)
print ()
print ("THANK YOU")
